# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='counter.proto',
  package='counter',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcounter.proto\x12\x07\x63ounter\"\x1d\n\x0c\x43ountRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32N\n\x0c\x43ountService\x12>\n\x0bsendRequest\x12\x15.counter.CountRequest\x1a\x16.counter.CountResponse\"\x00\x62\x06proto3'
)




_COUNTREQUEST = _descriptor.Descriptor(
  name='CountRequest',
  full_name='counter.CountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='counter.CountRequest.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=55,
)


_COUNTRESPONSE = _descriptor.Descriptor(
  name='CountResponse',
  full_name='counter.CountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='counter.CountResponse.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['CountRequest'] = _COUNTREQUEST
DESCRIPTOR.message_types_by_name['CountResponse'] = _COUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountRequest = _reflection.GeneratedProtocolMessageType('CountRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTREQUEST,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:counter.CountRequest)
  })
_sym_db.RegisterMessage(CountRequest)

CountResponse = _reflection.GeneratedProtocolMessageType('CountResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRESPONSE,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:counter.CountResponse)
  })
_sym_db.RegisterMessage(CountResponse)



_COUNTSERVICE = _descriptor.ServiceDescriptor(
  name='CountService',
  full_name='counter.CountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=89,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendRequest',
    full_name='counter.CountService.sendRequest',
    index=0,
    containing_service=None,
    input_type=_COUNTREQUEST,
    output_type=_COUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNTSERVICE)

DESCRIPTOR.services_by_name['CountService'] = _COUNTSERVICE

# @@protoc_insertion_point(module_scope)
